### ISSUE TITLE
Shows import costs text one line lower than it should be in .vue files

### ISSUE THREAD

**Issue by erkage** [hyrious/vscode-import-cost#2]
<img width="931" alt="Screenshot 2023-04-21 at 9 44 08" src="https://user-images.githubusercontent.com/4376696/233574985-d0e707df-4f2f-4493-87dc-7f1ee83479c1.png">
<img width="569" alt="Screenshot 2023-04-21 at 9 54 18" src="https://user-images.githubusercontent.com/4376696/233577235-6b1099f0-1502-40cd-ac29-2bfe50ab748c.png">

It happens in my main VSCode with lots of extensions but I've just freshly installed an Insiders version and it occurs there also.

It works fine in `.js` files.

VSCode version: 1.77.3
VSCode Insiders version: 1.78.0
System:  Apple M1 Pro / macOS 13.1

**Comment by hyrious** [comment]
Sorry, that's a mistake in calculating the line offset and I never tested. Will fix that in next release.

**Comment by erkage** [comment]
I can confirm that it's been fixed in the new version. Thanks!
